### ISSUE TITLE
[Safe Creation] Copy on the progress screen is misleading

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-monorepo#5615]
## Bug description

The user is told that their safe is being deployed and that they can check the progress below but there is nothing below

## Environment

- Browser: Chrome
- Wallet: MetaMask
- Chain: Base

## Steps to reproduce

1.  Go to app.safe.global
2. Create a Safe on Base via relay

## Expected result

There should be a link to the block explorer or the copy should be adjusted

## Obtained result

The copy is misleading and a link to block explorer is missing

## Screenshots

<img width="807" alt="Image" src="https://github.com/user-attachments/assets/ee632df0-153a-41b0-9554-3525d6cee13c" />

**Comment by aditya172926** [comment]
Ig this is fixed too @usame-algan @liliya-soroka . I see the explorer link while activating new account.
Can this issue be closed?

**Comment by liliya-soroka** [comment]
no, it was not fixed when the relay is used for the safe creation :

<img src="https://uploads.linear.app/cf187dcd-b206-4218-b688-803174268fff/37b6b0a3-8de4-4e1e-9bbe-2f0c57f3641c/b9b6483b-abe3-4691-a149-1dc94452852a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NmMTg3ZGNkLWIyMDYtNDIxOC1iNjg4LTgwMzE3NDI2OGZmZi8zN2I2YjBhMy04ZGU0LTRlMWUtOWJiZS0yZjBjNTdmMzY0MWMvYjliNjQ4M2ItYWJlMy00NjkxLWExNDktMWRjOTQ0NTI4NTJhIiwiaWF0IjoxNzY3NjAzNDQ5LCJleHAiOjE3OTkxNzQwMDl9.9DD4idR-wtC2k6mqVlh01PjVvGcGCjA7h-ZKZ5NXrEw " alt="image.png" width="915" data-linear-height="763" />

**Comment by aditya172926** [comment]
> no, it was not fixed when the relay is used for the safe creation :
> 
> <img alt="image.png" width="915" src="https://camo.githubusercontent.com/8ccf5793ba1019fd36a87979bf076295da45e98ca2c97a9824fa8ea6378f5518/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f63663138376463642d623230362d343231382d623638382d3830333137343236386666662f33376236623061332d386465342d346531652d396262652d3266306335376633363431632f62396236343833622d616265332d343639312d613134392d3164633934343532383532613f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c324e6d4d5467335a474e6b4c5749794d4459744e4449784f4331694e6a67344c5467774d7a45334e4449324f475a6d5a69387a4e324932596a42684d7930345a4755304c54526c4d5755744f574a695a5330795a6a426a4e54646d4d7a59304d574d76596a6c694e6a51344d32497459574a6c4d7930304e6a6b784c5745784e446b744d57526a4f5451304e5449344e544a684969776961574630496a6f784e7a59334e6a417a4e4451354c434a6c654841694f6a45334f546b784e7a51774d446c392e394444346964522d777443326b366d71566c683031506a5676476347436a4137682d5a4b5a354e5872457720">

Ok yeah. I see it now.

**Comment by aditya172926** [comment]
> no, it was not fixed when the relay is used for the safe creation :
> 
> <img alt="image.png" width="915" src="https://camo.githubusercontent.com/8ccf5793ba1019fd36a87979bf076295da45e98ca2c97a9824fa8ea6378f5518/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f63663138376463642d623230362d343231382d623638382d3830333137343236386666662f33376236623061332d386465342d346531652d396262652d3266306335376633363431632f62396236343833622d616265332d343639312d613134392d3164633934343532383532613f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c324e6d4d5467335a474e6b4c5749794d4459744e4449784f4331694e6a67344c5467774d7a45334e4449324f475a6d5a69387a4e324932596a42684d7930345a4755304c54526c4d5755744f574a695a5330795a6a426a4e54646d4d7a59304d574d76596a6c694e6a51344d32497459574a6c4d7930304e6a6b784c5745784e446b744d57526a4f5451304e5449344e544a684969776961574630496a6f784e7a59334e6a417a4e4451354c434a6c654841694f6a45334f546b784e7a51774d446c392e394444346964522d777443326b366d71566c683031506a5676476347436a4137682d5a4b5a354e5872457720">

I'd like to make a PR for this fix, if someone is not working on it already.
As per issue description, is the right fix is `Removing everything after ","` or having the transaction link below the message?
